name = "SMLMBoxer"
uuid = "a7d3b33b-b840-4f8e-b556-99be03134090"
authors = ["klidke@unm.edu"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
Flux = "0.14"
cuDNN = "1"
CUDA = "4, 5"
KernelAbstractions = "0.9"
SMLMData = "0.4"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
