name = "SMLMBoxer"
uuid = "a7d3b33b-b840-4f8e-b556-99be03134090"
authors = ["klidke@unm.edu"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"

[compat]
CUDA = "4, 5"
KernelAbstractions = "0.9"
NNlib = "0.9"
SMLMData = "0.5"
julia = "1.9"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Printf", "Statistics", "Test"]
