[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
MicroscopePSFs = "de9ac726-48a4-48ab-84b0-1c03c7c18929"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SMLMBoxer = "a7d3b33b-b840-4f8e-b556-99be03134090"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
